namespace System_Information
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App
    {
        public App()
        {
            Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("Mgo+DSMBaFt/QHJqVVhjWlpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF9jTnxSdkBnX35cc3JXRA==;Mgo+DSMBPh8sVXJ0S0R+XE9HcFRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS3xTcUdiWXpadnVXRWlVUg==;ORg4AjUWIQA/Gnt2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdkJhWH9bdHJURGReVUc=;NjgxMjgxQDMyMzAyZTMyMmUzMFlObmVZckNIblRXRmk4dTZUVmd1TS9MN015WXdFeXpTNk5IdE1UYlFSZjA9;NjgxMjgyQDMyMzAyZTMyMmUzMFFFb2pkSVY2YU5NeVVnRXNubUZrYWEwbDJMdjE2bkdJTUhTUGJwc0JyajQ9;NRAiBiAaIQQuGjN/V0Z+Xk9EaFxEVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdEVkW35edXBTR2JZU0d1;NjgxMjg0QDMyMzAyZTMyMmUzMGhoMGlrcUc5a2s5eUxkTkJtUENyL3VUTkRVR1ZRTzhZM1lDeHNFR1dlMVE9;NjgxMjg1QDMyMzAyZTMyMmUzMEM5Q2dtS2J6VExqeHFaRytpaXBpY3piN2YrUUJRV1ltMkEwZUZkM0FNZms9;Mgo+DSMBMAY9C3t2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdkJhWH9bdHJURGZZU0A=;NjgxMjg3QDMyMzAyZTMyMmUzMFdrYnNBdmN1c0d0VzFSUTlEZDk4d3NSOG9LVmtoOEhKaXBkNVpCYStBcjQ9;NjgxMjg4QDMyMzAyZTMyMmUzME1yb2VwSm1uZjFLTUl1cWloVStFRHk2UDNKTnJmam1PM0NFTlhoSUV4bEE9;NjgxMjg5QDMyMzAyZTMyMmUzMGhoMGlrcUc5a2s5eUxkTkJtUENyL3VUTkRVR1ZRTzhZM1lDeHNFR1dlMVE9");
        }
    }
}